### ISSUE TITLE
Something about CPU tweaks

### ISSUE THREAD

**Issue by aviraxp** [halogenOS/android_device_oneplus_oneplus2#3] opened 2016-08-08 05:03 UTC
Hey bro!I have something to say about the CPU tweaks.

I noticed that the min freq of our little cluster usually jumps to 1344MHz, which I think is uncessary and causes a lot of battery drain, even on powersave/ondemand mode. I even can't tweak with any app. The battery can only last for 4.5 hours while it can last for 6.5 hours. 

Is it because of
https://github.com/halogenOS/android_device_oneplus_oneplus2/commit/285d46bb49d1ddad26dcc90c4fdd04843ec1d766

**Comment by msfjarvis** [comment] 2016-08-08 06:10
I do not think that is the cause of the problem, since the script actually forces 3 out of 4 CPUs to go offline which should dramatically improve battery life. @xdevs23 and @regalstreak are better qualified to address your concern, but I'm closing this until further deliberation.

**Comment by regalstreak** [comment] 2016-08-08 06:11
Well does he face this problem on cm13? As it doesn't have this commit.

**Comment by aviraxp** [comment] 2016-08-08 06:14
No, I don't have the problem on other CAF/CM based roms. @regalstreak 

I don't think it is the commit that causes this problem as well.

**Comment by msfjarvis** [comment] 2016-08-08 06:15
@aviraxp I'll ready a test build with this reverted and we'll see if it really is the cause of the issue. That okay @regalstreak ?

**Comment by regalstreak** [comment] 2016-08-08 06:15
https://telegram.me/joinchat/BVYC_T-pjpv0kvKGmTvJNA

Join the testers group here. Will soon give out a build without that commit.

**Comment by xdevs23** [comment] 2016-08-08 06:19
I either picked that commit from @Altaf-Mahdi 's repo or from CM's, I'm not sure actually.

**Comment by msfjarvis** [comment] 2016-08-08 06:21
@xdevs23 looks like it's from Mahdi's repo, CM really doesn't have it.

**Comment by xdevs23** [comment] 2016-08-08 06:22
Yeah, I checked it on quick, it's from Mahdi, so revert this (dont rebase)

**Comment by xdevs23** [comment] 2016-08-08 06:23
@aviraxp Thank you very much for reporting, your contribution is important to us and our community.

**Closed as completed by xdevs23** 2016-08-08 06:22 UTC

**Comment by msfjarvis** [comment] 2016-08-08 06:26
Done

**Comment by xdevs23** [comment] 2016-08-08 06:26
Well done
